### ISSUE TITLE
Allow Users to give feedback on the label

### ISSUE THREAD

**Issue by dennyabrain** [tattle-made/Uli#125]

**Comment by Bhargav-Dave** [comment]
This feature is added and discussion on is is documented here:

https://github.com/tattle-made/OGBV/pull/223

To summarize: A new flag icon was added to the Uli interface whenever the user enables the ML feature. Upon pressing the flag icon, the user's user ID, tweet text, the label and the confidence will be sent to Uli's database for further review and a message saying 'Feedback Sent!' will appear on the Uli interface bar. 

The discussion summarizes an issue faced with the API calls not being made properly which was resolved after adding the feedback table made through sequelize to the index.js file.

**Comment by tarunima** [comment]
@dennyabrain should we close this?

**Comment by dennyabrain** [comment]
I think its not fully finished so lets keep it open. Will have to bring it into a spring and wrap up. Or if there's some urgent need for this.

Its def low priority as of now.

**Comment by Bhargav-Dave** [comment]
Got it, this issue is related so linking both the issues with each other. 

Is related to: https://github.com/tattle-made/OGBV/issues/232
