### ISSUE TITLE
Rewrite Existing Parser 

### ISSUE THREAD

**Issue by dennyabrain** [tattle-made/Uli#179]
We have a parser that goes through DOM data and extracts structured content out of it. twee_text, author, timestamp etc.
It can be seen here - https://github.com/tattle-made/OGBV/blob/main/browser-extension/plugin/src/twitter/parser.js

The current way to specify path for different components is very unwieldy and hard to debug  👍🏽 
```javascript
const TWEET_PATH_CLICKED = new RegExp(
        'DIV\\(0\\):DIV\\(0\\):DIV\\(0\\):DIV\\(0\\):ARTICLE\\(0\\):DIV\\(0\\):DIV\\(2\\):DIV\\(1\\):DIV\\(0\\):DIV\\(0\\):DIV\\(0\\):DIV\\(0\\):SPAN'
    );
```

Lets come up with a cleaner implementation for this and add tests.

**Comment by tarunima** [comment]
@dennyabrain can we close this?

**Comment by dennyabrain** [comment]
@Bhargav-Dave  i am closing this since its out of scope for now..lets reopen or reference this when we work on fixing the hyperlink issue on twitter.

**Comment by Bhargav-Dave** [comment]
Noted, that makes sense, we can create the relevant issues with pointed information about problems with the new parser
