### ISSUE TITLE
List of social impact projects using machine learning

### ISSUE THREAD

**Issue by tarunima** [tattle-made/Uli#248]
Assignees: Data Governance Researchers

**Comment by tarunima** [comment]
Might be emailing some projects to understand if they are crowdsourcing.

**Comment by sidm92** [comment]
Document for structure reference

Table reflects early thinking on AI for social good projects. Inclusive approach of looking at projects and orgs using AI to create value and reliant on crowdsourced annotation. Division by location on annotation value chain currently (annotation service provider/client etc)

https://docs.google.com/spreadsheets/d/1gnqpQ_fvpKLXRXb4KzUKTgbupwbJJsW-FZUokbSPCL4
