### ISSUE TITLE
Expand Slur redaction feature to more websites

### ISSUE THREAD

**Issue by tarunima** [tattle-made/Uli#254]

**Comment by dennyabrain** [comment]
Hey @duggalsu, I had a breakthrough. Pasting working code that I was able to use to find and replace text content on wikipedia.

```javascript
function dft(nodes){
    if(nodes.childNodes.length===0 && nodes.nodeType === 3){
        console.log("found leaf text node", nodes)
        nodes.textContent = nodes.textContent.replace("g", "🔥")
    }
    else{
        nodes.childNodes.forEach((nodes)=>dft(nodes))
    }
}

let body = document.getElementsByTagName("body")
let first_body = body[0]
let elements = first_body.children
let elements_array = Array.from(elements)
let relevant_elements = elements_array.filter((element)=>["P","DIV"].includes(element.nodeName))
for(const element of relevant_elements){
    dft(element)
}
```

Try pasting this in the console with Wikipedia open, it will replace all instances of the character "g" with the fire emoji. There might be edge cases in my logic but see if you can find any reason why this is not an acceptable solution.

**Comment by dennyabrain** [comment]
I called my function dft, because i thought i'm doing depth first traversal. Just realized this might be better named bft for breadth first traversal.

**Comment by duggalsu** [comment]
Hey @dennyabrain , I was also toying with nodeType earlier but this code is working successfully with minor edge-case handling and optimization. It is also handling `<li>`, `<a>` elements without any modification. Haven't seen any issues with `<span>` yet. No site seems to be breaking now.

**Comment by dennyabrain** [comment]
@duggalsu With respect to listening for continuous changes, I got this unoptimized code working on reddit

```javascript
function dft(nodes){
    if(nodes.childNodes.length===0 && nodes.nodeType === 3){ 
        console.log("found leaf text node", nodes)
        nodes.textContent = nodes.textContent.replace("g", "🔥")
    }
    else{
        nodes.childNodes.forEach((nodes)=>dft(nodes))
    }
}


let body = document.getElementsByTagName("body")
let first_body = body[0]



const config = { attributes: true, childList: true, subtree: true };
const callback = (mutationList, observer) => {
  let elements = first_body.children
let elements_array = Array.from(elements)
let relevant_elements = elements_array.filter((element)=>["P","DIV"].includes(element.nodeName))

for(const element of relevant_elements){
    dft(element)
}

} 
const observer = new MutationObserver(callback);
observer.observe(first_body, config); 
```

There is a lot of documentation on MutationObserver [here](https://developer.mozilla.org/en-US/docs/Web/API/MutationObserver) that I haven't read fully. And its quite possible that in my code above, our on change callback gets called a lot more than it should be. Can you first evaluate if this is a good solution and if yes, see if we can reduce the number of processing from our side?
