### ISSUE TITLE
Create Attribution for Slur List

### ISSUE THREAD

**Issue by dennyabrain** [tattle-made/Uli#312]
**Is your feature request related to a problem? Please describe.**
We're increasingly showing around the Uli slur list itself as a resource. We should provide an easily visible attribution for the slurlist. 

**Describe the solution you'd like**
A simple text blurb that can go on the github file where the slurs are tracked. It can also go in the text files where we save the slurs. It can also go on any webpage we create for the slur list. This should inspire confidence in the users that the slur list is meant to be reused. It will also bring in visibility to our projects via their projects.

**Describe alternatives you've considered**
Uli itself is GPL-3 and the slur list is on the repo so if anyone wanted they could attribute by linking to it. My proposed feature is a nice-to-have improvement over it.

**Comment by tarunima** [comment]
I assume that if I add license terms at the top of the slur list file on GitHub, it will mess up the redaction feature? https://github.com/tattle-made/Uli/blob/main/browser-extension/plugin/scripts/slur-list.txt

**Comment by tarunima** [comment]
@dennyabrain if the list is not being actively used for redaction I am going to add the license on top.
