### ISSUE TITLE
To make sure all the sendMessage() are cross-platfroms

### ISSUE THREAD

**Issue by aatmanvaidya** [tattle-made/Uli#325]
Currently, the sendMessage() is being called via chrome, instead, it should be cross platform (firefox etc.). 

https://github.com/tattle-made/Uli/blob/20c1eaf2ac34620796a38cec23ffdc46ce518cbb/browser-extension/plugin/src/background.js#L13-L34

**Comment by sathuhebbar** [comment]
I would like to work on this issue, but would you please describe the issue to me a little bit more in detail?

**Comment by aatmanvaidya** [comment]
Hello @sathuhebbar , I will explain this issue to you

Uli is a browser extension that primarily works on two browsers - **Chrome and Firefox**

Each browser extension has a file called `content-script.js`. [Content scripts](https://developer.chrome.com/docs/extensions/mv3/content_scripts/) are files that run in the context of web pages. By using the standard [Document Object Model](https://developer.mozilla.org/docs/Web/API/Document_Object_Model) (DOM), they are able to read details of the web pages the browser visits, make changes to them, and pass information to their parent extension. Uli uses this to enable some of its core-features. 

Communication between extensions and their content scripts works by using message passing. Either side can listen for messages sent from the other end, and respond on the same channel. If you only need to send a single message to another part of your extension (and optionally get a response back), we can use a thing called `chrome.tabs.sendMessage()`. [This](https://developer.chrome.com/docs/extensions/reference/tabs/#method-sendMessage) sends a single message to the content script(s) in the specified tab, with an optional callback to run when a response is sent back. 

Since we essentially have the same code for the browser extension to run in chrome and firefox. It is important that we make `sendMessage()` cross platform. For instance `sendMessage()` in Firefox can be used as `browser.tabs.sendMessage()` - [doc](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/tabs/sendMessage). 

A good example of cross-platform code in Uli can be found here.
https://github.com/tattle-made/Uli/blob/fc3f0784d6fced0cc4d821bba0924ae549a6c445/browser-extension/plugin/src/ui-components/pages/App.jsx#L69-L83
In the above code snipppet, we first identify which browser it is and then store it in the `userBrowserTabs` variable. Next to use `sendMessage()`, in the same we file, we do it like this
https://github.com/tattle-made/Uli/blob/fc3f0784d6fced0cc4d821bba0924ae549a6c445/browser-extension/plugin/src/ui-components/pages/App.jsx#L103-L135
As you can see, in this function, `sendMessage()` is made cross-platform. 

## **What should be done in the Issue?**

There is a code snippet in this [file](https://github.com/tattle-made/Uli/blob/main/browser-extension/plugin/src/ui-components/pages/Preferences.jsx), where `sendMessage()` is not cross-platform, the message is sent via `chrome`
https://github.com/tattle-made/Uli/blob/fc3f0784d6fced0cc4d821bba0924ae549a6c445/browser-extension/plugin/src/ui-components/pages/Preferences.jsx#L92

We don't want that, the issue is to make this cross-platform. 

### To work on this Issue
1. You will first have to setup Uli locally for development - This will help you [Link1](https://youtu.be/fwSnEe3-fL8), [Link2](https://github.com/tattle-made/Uli/wiki#setup-guides)
2. Make it cross-platform as explained


PS - Please dont hesitate to reach out to us if you face any issue. Feel free to join our Slack and interact with us

**Comment by abhishek-nigam** [comment]
Hi @aatmanvaidya Thank you and all maintainers for this project! Can I work on this issue? Though I haven't worked with browser extensions before, I do have experience writing JavaScript. I think it'll be a good learning experience for me.

**Comment by aatmanvaidya** [comment]
Hello @abhishek-nigam, please feel free to take this issue up, experience with JavaScript is always a plus. 

To setup the Uli browser extension: 
1. you can follow this video - https://youtu.be/fwSnEe3-fL8
2. also follow the setup instructions in this guide on our wiki - https://github.com/tattle-made/Uli/wiki#setup-guides

If you wish to take this issue up, let me know, I will assign it to you

Feel free to reach out, if you need any help

**Comment by abhishek-nigam** [comment]
Thanks! Sure @aatmanvaidya, I'll work on it

**Comment by abhishek-nigam** [comment]
Hi @aatmanvaidya ,

I'm having an issue getting the dev setup to run. I followed the YouTube walkthrough as well as the Wiki guide. But as soon as I click on the extension's icon in Chrome, it gives some errors which are collected by Chrome and shown. I have made a screen recording to show the error:

[Screencast from 10-10-2023 11:15:34 PM.webm](https://github.com/tattle-made/Uli/assets/21065165/8eb49b9b-940a-467b-b43a-aebb490235ac)

Could you help me with it?

**Comment by aatmanvaidya** [comment]
Hi @abhishek-nigam , what happens when you click on `Activate Account`, **ignore** the errors on chrome for now. 

Still, if its convenient, for you, join our slack (link in readme), we can get on a call and I can help you fix this. you can drop a message in the `uli_issues_hacktoberfest` slack channel.

**Comment by abhishek-nigam** [comment]
Sure @aatmanvaidya I'll do ahead and do that.

**Comment by abhishek-nigam** [comment]
Hi, I've raised a PR for it here https://github.com/tattle-made/Uli/pull/401 @aatmanvaidya

**Comment by aatmanvaidya** [comment]
Hi @abhishek-nigam , will take a look soon, hope you were able to run the browser extension?

**Comment by abhishek-nigam** [comment]
Nopes :(

**Comment by abhishek-nigam** [comment]
Nope, I wasn't able to run the extension. Nothing happens when I click on 'Activate Account'

**Comment by aatmanvaidya** [comment]
This issue has been resolved - https://github.com/tattle-made/Uli/pull/401
