### ISSUE TITLE
Streamline the documentation to reduce the onboarding time for new contributors

### ISSUE THREAD

**Issue by dennyabrain** [tattle-made/Uli#331]
**Is your feature request related to a problem? Please describe.**
Current documentation is scattered and not upto date.

**Describe the solution you'd like**
Create a clear index on the main `README.md`. Consolidate the readme's and docs scattered through the repo. Organize it all in the repo wiki. Bring in the text @kaustubhavarma is working on wrt github onboarding and uli team contact details.

**Comment by dennyabrain** [comment]
Please feel free to post reference repos and projects you have in mind to spark some inspiration and discussion around this.

**Comment by dennyabrain** [comment]
I really like how the Flutter wiki is organized : https://github.com/flutter/flutter/wiki
Their sidebar is especially well organized and thought out
![Screenshot 2023-08-18 at 10-28-31 Home](https://github.com/tattle-made/Uli/assets/1415361/d266c331-cd1a-4f66-89ee-05c9307f33ba)

The dearrow browser extension [readme](https://github.com/ajayyy/DeArrow) is also very nice. Has great screenshots from the extension itself. Very effective I think in communicating what the project does

**Comment by kaustubhavarma** [comment]
Preliminary checklist for the wiki:
(ref:https://github.com/hackforla/website/wiki)
Onboarding:

- [ ] What is Uli

- [ ] How do I Contribute?

- [ ] How can I communicate with the team?
- [ ] Giving weekly progress updates
- [ ] Helping a team member with their blockers
- [ ] FAQs- 
- [ ] Whom to contact if you miss a meeting
- [ ] You’re making a point but someone is talking over you
- [ ] How you can ask for help
- [ ] Your pull request has not been reviewed for days
- [ ] How you can set up private meetings with the dev(s)
- [ ] You want to take time off.
- [ ] You want to leave. Here’s what you do.

For Developers:

- [ ] Site Architecture
- [ ] Github Actions
- [ ] Interpreting issue labels
- [ ] Creating Pull Requests
- [ ] Creating Issues

External Links:

- [ ] Website

**Comment by aatmanvaidya** [comment]
This is a blog post for setting up Uli locally for coding and development. 
This could be helpful to add in the Developers section of the wiki - 
https://tattle.co.in/blog/how-to-setup-uli-locally

**Comment by dennyabrain** [comment]
@aatmanvaidya thanks for the blog! its a great first step.

I was going through the blog and my immediate reaction was that there's too many CONDITIONALs in our setup step. 
for instance if you are on windows, do this. If you are on firefox do this. This also makes the setup steps very daunting to a newbie.

It made me think of what Gurpreet told us about his project Bahmi's developer setup instructions.
He said that often people google for thigns like "Setup Bahmi on windows" or "setup Bahmi on CentOS" or "setup Bahmi using Docker". Now Bahmi is supported on all those platforms, but instead of having ONE large document with all instructions, they've made separate documents for each platform. So for isntance : 
- https://bahmni.atlassian.net/wiki/spaces/BAH/pages/299630726/Running+Bahmni+on+Docker
- https://bahmni.atlassian.net/wiki/spaces/BAH/pages/33128505/Install+Bahmni+on+CentOS
- https://bahmni.atlassian.net/wiki/spaces/BAH/pages/115915906/Install+Bahmni+on+Windows
- https://bahmni.atlassian.net/wiki/spaces/BAH/pages/34439320/Install+Bahmni+on+Cloud+Digital+Ocean

I think this is great. Because a developer who primarily works on windows doesn't need to read about linux idiosyncracies in the setup instructions. Even when I am onboarding a new developer to Uli, I have to constantly second guess what platform they are on and if thats the cause for issues.

In addition to a common setup guide, we can consider breaking the setup into multiple files like : 
- Setup Uli on Windows for Chrome
- Setup Uli on Windows for Chrominum Browsers (Brave, Kiwi etc)
- Setup Uli on Windows for Firefox
- Setup Uli on Windows for Firefox for Android
- Setup Uli on Linux for Chrome
- Setup Uli on Linux for Chrominum Browsers (Brave, Kiwi etc)
- Setup Uli on Linux for Firefox
- Setup Uli on Linux for Firefox for Android

We don't have any Mac users in the dev community so far so its ok to skip it for now 😛. Most likely the Linux instructions should suffice for now 🤷🏽‍♂️

**Comment by dennyabrain** [comment]
note to @duggalsu, maybe you can takeup writing the SECURITY.md file for this issue?
note to self, setup a Pull Request Template to enforce a common standard to raising PRs, testing and reviews

**Comment by dennyabrain** [comment]
We should put this cartoon in a "how to help" section
https://twitter.com/b0rk/status/1696602073351979340
![julia-contributor-comic](https://github.com/tattle-made/Uli/assets/1415361/c049653b-a74e-414b-83a3-63873ad36757)

**Comment by kaustubhavarma** [comment]
The Wiki has been updated and I've added the following pages:

- Home page
- About Us (linked to the ReadMe)
- Our Team
- Contributing to Uli
- Code of Conduct (linked to the existing one)
- Internal Communications
- Issues and Triaging

I will create the FAQs section and compile a few common ones.

**Comment by kaustubhavarma** [comment]
The FAQ section is now up as well. For now it has a few general ones, please include any common questions relating to the technical aspects of contributing. If any of us face any general hiccups that we think should feature on our Wiki/FAQ, let's add to the relevant section.
