### ISSUE TITLE
Automations to help expedite PR reviews and QA

### ISSUE THREAD

**Issue by dennyabrain** [tattle-made/Uli#347]
**Is your feature request related to a problem? Please describe.**
We need a way for all tattle members to quickly try out changes in a new PR without having to setup a dev environment. This will enable anyone on the team to help review a PR and share feedback. It will greatly expedite feature releases.

**Describe the solution you'd like**
Anytime a PR is made, we should run some automations and share in the comments like this - https://github.com/tattle-made/website/pull/126#issuecomment-1695788598
At the least we should build the required zip files for chrome and firefox that a user can just download from the comment and add to their local machine.

**Describe alternatives you've considered**
None

**Additional context**
We need to ensure that these built extensions communicate with the **staging server** and not the production server.
In the app UI where it says development or production, we could add a "staging" label so the tester is always sure.
We will conduct a special session with all team members to walk them through how they can help expedite open PRs. @kaustubhavarma would join too and this could be an easy thing to get contributor support for.

**Comment by aatmanvaidya** [comment]
Are we looking for something like this? - https://github.com/syndesisio/pure-bot

**Comment by dennyabrain** [comment]
Since I am more familiar with writing/using github actions, I might see if we can start this off with a github action itself. We'll configure the action to trigger when a new PR is made. We already are able to run npm commands in an action. There is a way to attach artefacts (in this case the built extension) to the running workflow. Then we need to figure out if there is a way to comment on the PR from the github action AND link the artefacts.

**Comment by aatmanvaidya** [comment]
so, in our case, the action would be `npm run dev:chrome` or `npm run dev:firefox` right?

So, if I understand correctly, the artefacts (build files) should also be directly uploaded in your browser? 
so essentially, the backend and hosting of this artefact will be taken care by the GitHub actions? 

something like this? - https://spacejelly.dev/posts/how-to-create-a-custom-github-action-with-node-javascript/

**Comment by dennyabrain** [comment]
So to build the testing ready artefacts, we will have to run some equivalent of npm run build.
We have an existing precedent here : 

https://github.com/tattle-made/Uli/blob/93eab95d7ed8357de4ccc0c52325cfba7ff703cc/.github/workflows/create-plugin-release.yml#L28C1-L38C47

which runs the npm run build command and creates zip files.

Of course the change we'll have to make is that we wouldnt want our extension to talk to the production server but instead to a new staging server thats meant for testing.

so we know how to trigger a workflow and how to build the extension in a github action. What we've not done ever is use the action to post a comment on the same PR which triggers the action.
This action could be relevant - https://github.com/marketplace/actions/add-pr-comment

and another unknown for me is how do you get a link to the built artefacts (zip files) so that it can be posted in the comment automatically.

**Comment by aatmanvaidya** [comment]
This directly might not be a part of this issue, but will help us automate things and make Uli development seamless. 

One issue is we need scripts in `browser-extension/plugin/package.json` cross-platforms. Here are some ways to do it 
1. We could use NPM packages that support this like - 
https://www.npmjs.com/package/run-script-os
https://stackoverflow.com/questions/45082648/npm-package-json-os-specific-script
https://www.npmjs.com/package/cross-env
https://stackoverflow.com/questions/41548990/how-to-create-cross-platform-scripts-multiple-command-for-single-line-in-packa
2. We could write seprate npm scirpts for each OS, this is a blog that gives some more insight - https://web.archive.org/web/20220722094802/https://docgov.dev/posts/npm-scripts/

**Comment by dennyabrain** [comment]
yes, good catch. I think parcel has a command `parcel clean` which deletes all parcel related files. We can add that to the dev:clean script.

**Comment by dennyabrain** [comment]
We also need to investigate what are some testing practices we can add to atleast ensure our core features are automatically tested everytime a new PR comes. Doing end to end testing on browser extensions that runs on all platform doesn't seem to be a solved problem. Every framework i find seems to lack support for one browser. eg puppeteer that supports loading and testing extensions on chrome but not firefox - https://pptr.dev/guides/chrome-extensions

Its been a while since i evaluated this. so lets look at what we can do.  @duggalsu is doing preliminary exploration on this.

**Comment by dennyabrain** [comment]
Also in this scope would be standardizing our API testing methodology. Either curl, hoppscotch/postman or scripts (node would be apt for this project). I would prefer it to be something code based and not involve GUI like hoppscotch/postman. but given that issue we had with file uploads on the `archive` endpoint, that might be tricky. so lets see whats our most automation friendly option now.

**Comment by aatmanvaidya** [comment]
## Step 1 - Make sure the github action runs on a pull request
We can do so by adding this in our github action
```yaml
on:
  pull_request:
    branches:
      - <TARGET_BRANCH>
```

## Step 2 - Make sure to upload the dist folder as a github action artifact
We can do so by adding this in our github action
```yaml
 - name: "Upload extension.zip as artifact"
        uses: actions/upload-artifact@v3
        with:
          name: extension
          path: browser-extension/plugin/extension.zip
```

## Step 3 -

**Comment by dennyabrain** [comment]
perfect! I think this is it :)
when you try this out, can you check how the upload-artifact action can be used to upload 2 artefacts? 
Ideally we'd like to build 2 zip fiies - one for firefox and one for chrome.
