### ISSUE TITLE
window.confirm() doesn't show text in firefox

### ISSUE THREAD

**Issue by aatmanvaidya** [tattle-made/Uli#351]
window.confirm() doesn't show the text inside in this code block (line 88) on Firefox. 

https://github.com/tattle-made/Uli/blob/93eab95d7ed8357de4ccc0c52325cfba7ff703cc/browser-extension/plugin/src/ui-components/pages/App.jsx#L85-L101

This is what is happening.

![Screenshot (496)](https://github.com/tattle-made/Uli/assets/56875084/8d37e4ca-e6a9-4e6b-a66c-48ed12128277)

But, window.confirm() shows the text in another code block. In this function on line 109, the text appears in the browser. 
https://github.com/tattle-made/Uli/blob/93eab95d7ed8357de4ccc0c52325cfba7ff703cc/browser-extension/plugin/src/ui-components/pages/App.jsx#L103-L111

Like this

![Screenshot (497)](https://github.com/tattle-made/Uli/assets/56875084/d6235f8f-18d8-4844-9b59-41b7a0c07ee4)

**Comment by priyanshtiwari001** [comment]
Hi @aatmanvaidya, I love to work on this issue and try to resolve it. Could you please assign this to me. Thank you!

**Comment by aatmanvaidya** [comment]
Hello @priyanshtiwari001, yes feel free to take this issue up. I am assigning it to you.

don't hesitate to join our Slack channel and engage with us if you encounter any challenges. (Slack link in the main readme)

**Comment by priyanshtiwari001** [comment]
Hi @aatmanvaidya , I can't find the solution of this issue. Kindly please assign to other person. Thank you!

**Comment by aatmanvaidya** [comment]
Thank you for giving it a shot @priyanshtiwari001, is there anything that we can do from our side to help you out?

If you have any relevant links/ findings that you have made which you think will help the future contributor, please add then to this issue, it will be of great help.
