### ISSUE TITLE
Remote Contextual Inquiry Sessions with P2

### ISSUE THREAD

**Issue by tarunima** [tattle-made/Uli#352]
This is a continuation from #334. We followed up with members of P2 to schedule a remote CI session for specific tasks in their day. The observation sessions will happen in this iteration.

**Comment by dennyabrain** [comment]
Notes from Devika Session are [here](https://app.nuclino.com/TattleRattle/Tattle-Docs/Devika-CI-b15b6f9f-b6ce-4689-b95c-3e059aea3dee)
