### ISSUE TITLE
Literature review - (First iteration)

### ISSUE THREAD

**Issue by sidm92** [tattle-made/Uli#353]
Data governance

Currently a list of academic and non-academic articles, and some information pages from product sites (13 September 2023)

**Comment by sidm92** [comment]
Link list

- https://responsibledata.io/
- 
- https://techcrunch.com/2019/03/10/appen-acquires-figure-eight/

- https://www.wsj.com/podcasts/the-journal/the-hidden-workforce-that-helped-filter-violence-and-abuse-out-of-chatgpt/ffc2427f-bdd8-47b7-9a4b-27e7267cf413

- https://www.404media.co/inside-the-ai-porn-marketplace-where-everything-and-everyone-is-for-sale/

https://www.computerweekly.com/news/252512896/EC-proposes-new-directive-to-improve-gig-economy-work-conditions

https://www.computerweekly.com/news/366546273/AI-interview-Krystal-Kauffman-lead-organiser-Turkopticon

https://foundation.mozilla.org/en/blog/mapeo-helps-marginalized-communities-collect-data-reclaim-land-rights/

https://gdc.cancer.gov/

https://m14intelligence.com/public/index.php/blog/41

https://aapti.in/blog/just-and-equitable-data-labelling/

https://fair.work/wp-content/uploads/sites/17/2021/12/Fairwork-India-Report-2021-accessible.pdf

#GIG WORK https://onlinelibrary.wiley.com/doi/epdf/10.1002/hrm.22168

https://www.theverge.com/2023/4/19/23689879/ai-drake-song-google-youtube-fair-use

https://www.washingtonpost.com/world/2023/08/28/scale-ai-remotasks-philippines-artificial-intelligence/

https://restofworld.org/2023/exporter-industry-behind-ai/

https://fiftytwo.in/story/human-touch/

https://www.theverge.com/features/23764584/ai-artificial-intelligence-data-notation-labor-scale-surge-remotasks-openai-chatbots

**Comment by dennyabrain** [comment]
Have to classify and label next.

**Comment by sidm92** [comment]
https://scholarspace.manoa.hawaii.edu/server/api/core/bitstreams/7f5b8ab1-505f-4aa2-9b0d-10611496f552/content
