### ISSUE TITLE
Turn Github Issue templates into forms

### ISSUE THREAD

**Issue by dennyabrain** [tattle-made/Uli#361]
**Is your feature request related to a problem? Please describe.**
We would like to use Github to capture feature requests and bugs by our users. Right now we direct them to create a new issue on github for the same. The present flow expects them to be able to correctly parse and write a markdown file. A lot of our users will be non developers and so it would be nice to provide a more user friendly UI to them.

**Describe the solution you'd like**
I noticed that github allows you to define a customizex UI for via issue templates. As you see in this image.
![sample-issue-form-2](https://github.com/tattle-made/Uli/assets/1415361/e552c931-af9b-4bfb-9cb2-6580e98d6450)
This appears as an interactive web form to the user with checkboxes, dropdowns and what not. This should help us get feedback effectively.

**Describe alternatives you've considered**
I have considered using a third party tool that is specialized for taking user feedback. Github CAN be a little tricky for others. But the userbase size does not justify getting into a new tool. On the contrary @kaustubhavarma's github guide makes it a bit easy for new people to get onboarded to our Github profile. So if a super user wants to give us feedback, we can spend time with them and onboard them on github first as part of our welcome flow.

**Additional context**
- Use this [official guide](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository) by github
- Our current templates files are [here](https://github.com/tattle-made/Uli/tree/main/.github/ISSUE_TEMPLATE). I believe these will need to be replaced with the syntax mentioned in the above link.

**Comment by aatmanvaidya** [comment]
@dennyabrain I can take this up, some more context will be required for me to get started working on this. But I can definitely take this up and give it a shot.

**Comment by dennyabrain** [comment]
Haan cool. It's not a high priority item. We'll schedule it on a sprint plan meeting sometime. Or if you are free someday take it up and add it to the planner

**Comment by plon-Susk7** [comment]
Hi @aatmanvaidya can I work on this issue?

**Comment by aatmanvaidya** [comment]
hi @plon-Susk7 , yes please feel free to take it up, let us know if you need any help.

**Comment by plon-Susk7** [comment]
Hi @dennyabrain , how can I test out my code for this issue?

**Comment by dennyabrain** [comment]
Good question, I think you can just do it on a dummy repo of your own and link it here.

**Comment by plon-Susk7** [comment]
Sure, thanks.

**Comment by plon-Susk7** [comment]
Hi @dennyabrain @aatmanvaidya Here's the git repo where I tested the yaml code: https://github.com/plon-Susk7/demo_template, please review my PR. Thanks.
