### ISSUE TITLE
well defined styles for code blocks in mdx files

### ISSUE THREAD

**Issue by aatmanvaidya** [tattle-made/Uli#382]
**Is your feature request related to a problem? Please describe.**
We need to have well defined styles for code blocks for content rendered by mdx files. 

As of now, code blocks are being rendered on the website in a blog like this.
See this blog - https://uli.tattle.co.in/blog/getting-started-with-aws-copilot

![Screenshot from 2023-09-25 13-02-15](https://github.com/tattle-made/Uli/assets/56875084/6fd0a04e-1b9c-4e4b-865e-79ba9ee3ea43)

**Describe the solution you'd like**
We need well defined code formatting styles for code blocks in mdx files.

**Comment by plon-Susk7** [comment]
Hi, I'd like to work on this issue :)

**Comment by aatmanvaidya** [comment]
@plon-Susk7 feel free to take it up, assigning it to you
