### ISSUE TITLE
Fix GitHub Action for PR Review

### ISSUE THREAD

**Issue by aatmanvaidya** [tattle-made/Uli#388]
**Describe the bug**
We have a github action that builds the `dist` folder of the `browser-extension` and uploads that as github artifcats.
Github action - `.github/workflows/build-pr-review-both-browsers.yml`
https://github.com/tattle-made/Uli/blob/main/.github/workflows/build-pr-review-both-browsers.yml

We want to make some changes to this, right now just the `dist` folder is being uploaded as a github artifact, we now want this artifcat link to show in the UI of the pull request as a comment. 
something like this 

![271206321-785aacac-05e5-4b5b-9c5f-21ab109dabb2](https://github.com/tattle-made/Uli/assets/56875084/6035da75-983b-4646-8a64-478ed3bbfa37)

We tried using `actions/github-script` for this, but it is not possible doing that. 
The first task of this issue would also be to investigate whether something like this is possible or not. 

**To Reproduce**
This workflow is triggered when a pull request is made for the `main` branch of `tattle-made/Uli`. 
If you are facing any issues, please reach out to @aatmanvaidya.

**Expected behavior**
A comment should be seen in the UI of the pull request with artifcat link.

**Comment by chinmaym07** [comment]
Hi @aatmanvaidya, Can I contribute to this ?

**Comment by aatmanvaidya** [comment]
@chinmaym07 yes definitely, feel free to take this up!

You can keep updating us with your progress here on the comments of the issue

**Comment by Drex72** [comment]
hey @aatmanvaidya  , i can't see what the image that you posted up there , thereby not allowing me to know how the artifact link should look
could you please help me check it out?

**Comment by aatmanvaidya** [comment]
Hi @Drex72 , I have re-uploaded the image, is it visible to you know?

**Comment by Drex72** [comment]
> Hi @Drex72 , I have re-uploaded the image, is it visible to you know?

yh, it is
thanks

**Comment by plon-Susk7** [comment]
hi @aatmanvaidya , can I work on this issue?

**Comment by aatmanvaidya** [comment]
Hello @chinmaym07 , are you working on this issue? have you made any progress?

If not, please do let us know, we can assign it to @plon-Susk7. 

@chinmaym07 if you need help in anything, please don't hesitate to reach out to us.

**Comment by aatmanvaidya** [comment]
@plon-Susk7 Please feel free to take this issue up

@chinmaym07 I am assigning this issue to @plon-Susk7

**Comment by aatmanvaidya** [comment]
Hi @plon-Susk7 , 
As Hacktoberfest is almost coming to an end, I wanted to check in and see if you're still actively working on the issue. It would be great to know your current status so that we can plan accordingly.

Please don't hesitate to reach out in case you need any help.
