### ISSUE TITLE
Add fields for annotation by partners on the UI

### ISSUE THREAD

**Issue by tarunima** [tattle-made/Uli#389]
We've tested the lexicon with the two partner organizations. The metadata fields may change in the future but not dramatically. 

For reference:
- Annotation guideline (for meaning of each label): https://docs.google.com/document/d/18H4TlLFB2GXK054oMj1uXVJ2OCFW08Gi/edit
- partner annotations here: https://docs.google.com/spreadsheets/d/15YrV8Q-5PTorHRo71ZBkdL0bePPaUNC9FTU41ET91V4/edit#gid=0

These are the fields that we need for now:

| Field Name    | Field Type |  Possible Values |  Optional?|
| ------------- | ---------- |----------------- |------- |
| Level of Severity  |  Single option | low, mid, high  | No |
| Casual  |  Binary | Yes, No  | No |
| Appropriated  |  Binary | Yes, No  | No |
| If, Appropriated is it by community or others?  |  Binary | Community, Others  | yes |
| What makes it problematic?  |  Text |        | yes |
| Category of Abuse |   pick multiple |  gendered, sexualized, religion, ethnicity , political affiliation, caste, class, body shaming,  abelist,  sexual identity,  other | pick at least one, at most 4 |
--------------------------------------------------

**Comment by aatmanvaidya** [comment]
@tarunima The field for the Slur (labe) and its meaning (label meaning), I will also have to add those right?

**Comment by dennyabrain** [comment]
ccing aatman's PR on this - https://github.com/tattle-made/Uli/pull/364

**Comment by dennyabrain** [comment]
Accessibility Criteria : 

- [ ] Curate web pages with slurs so that it can be used to demo the "crowdsource feature"

**Comment by aatmanvaidya** [comment]
web pages with slurs 
1. https://sharechat.com/tag/Bb7BlV/fresh
