### ISSUE TITLE
Conceptual framework document

### ISSUE THREAD

**Issue by sidm92** [tattle-made/Uli#403]
Documentation of conceptual framework from calls - Academic interviewees

Notes-based brief - Wed 18 October

**Comment by dennyabrain** [comment]
Moved from Iteration 1 (Oct 16-Oct 29) to Iteration 2(Oct 30 - Nov 12)

**Comment by sidm92** [comment]
WIP document shared on 3rd Nov

**Comment by sidm92** [comment]
Recieved comments: to update the document with literature review materials; academic articles; and documentation form Annotation companies.
Theoretical framework, not simply learnings.

Nuclino link:

**Comment by sidm92** [comment]
Updating doc - 6th nov

**Comment by sidm92** [comment]
Abstract added:

https://app.nuclino.com/TattleRattle/Tattle-Docs/Framework-draft-rough-ce38fa1f-3ed3-4be3-adc6-6b3385e48726

**Comment by tarunima** [comment]
I will review it by tomorrow and revert back with comments.

**Comment by sidm92** [comment]
To add more sources especially and any missing arguments. Build out body of report.
