### ISSUE TITLE
Improve UI for Slur Crowdsource Feature

### ISSUE THREAD

**Issue by aatmanvaidya** [tattle-made/Uli#409]
### Is your feature request related to a problem? Please describe.

In the latest release of Uli v0.1.14 - https://github.com/tattle-made/Uli/releases/tag/v0.1.14

In the crowdsource feature users can now crowdsource slur's and its relevant metadata using Uli. A user can select and right-click on a word to crowdsource it.

The metadata helps in providing better context to slur words. Metadata that can be crowd sourced for a slur is:
1. Level of Severity
2. Casual
3. Appropriated
4. If Appropriated, is it by community or others?
5. What makes it problematic?
6. Category of Abuse

More details about the feature can be found in this issue - https://github.com/tattle-made/Uli/issues/389

We are displaying the all the data in a box that looks like this

<img src="https://github.com/tattle-made/Uli/assets/56875084/30e42427-01f6-4adc-b175-0ef674adf2a6" width="400" height="500">

All the current code for this can be found it here - `browser-extension/plugin/src/ui-components/atoms/SlurCard.js`
https://github.com/tattle-made/Uli/blob/main/browser-extension/plugin/src/ui-components/atoms/SlurCard.js

We use the Grommet component library for frontend. - https://v2.grommet.io/

## The task is to change the box to a grommet card component. 

1. I have written some code of the card component in this file - `browser-extension/plugin/src/ui-components/atoms/SlurCardComponent.js`
https://github.com/tattle-made/Uli/blob/main/browser-extension/plugin/src/ui-components/atoms/SlurCardComponent.js

This is the Grommet Card Component - https://v2.grommet.io/card

The task is just to complete the code, you have to make sure that everything is responsive and no text overflows etc. 

If there is any other way to also display all the text/ content in the box, please feel free to suggest us those changes.

**Comment by ashishpetwal** [comment]
Hello there, I would like to work on this issue. Could you provide me with more details about it?

**Comment by aatmanvaidya** [comment]
Hello @ashishpetwal , I have revised the issue and made some changes to the description, please let me know if any more clarifications are required. 

The task is just to code the above box seen into a grommet card component. 

Please let me know if any other help / clarification is needed

**Comment by ashishpetwal** [comment]
Ok Fine! You can assign the issue to me.

**Comment by aatmanvaidya** [comment]
Hello @ashishpetwal, 
As Hacktoberfest is almost coming to an end, I wanted to check in and see if you're still actively working on the issue. It would be great to know your current status so that we can plan accordingly.

Please don't hesitate to reach out in case you need any help.

**Comment by ashishpetwal** [comment]
Sorry for late, I was busy in some other things. You can assign the issue to someone else.

**Comment by ckirby19** [comment]
Hello, is this issue still open to be worked on?

**Comment by aayushk9** [comment]
> Hello @ashishpetwal , I have revised the issue and made some changes to the description, please let me know if any more clarifications are required.
> 
> The task is just to code the above box seen into a grommet card component. Grommet is the component library that we use in our frontend. This issue involves writing code in JavaScript
> 
> Please let me know if any other help / clarification is needed

Great, I can work on implementing this!

**Comment by utnim2** [comment]
on starting the uli chrome extension locally , when i click on activate account this error is popping

![image](https://github.com/tattle-made/Uli/assets/127925465/9f20083c-d3a6-4546-83f2-e4a3e7e179e6)
any idea to resolve it ?

cc @dennyabrain @ckirby19

**Comment by hardik-pratap-singh** [comment]
Hello @aatmanvaidya @dennyabrain 
I have worked on this issue for UI improvement 

Results : 

![Screenshot from 2024-04-24 12-04-38](https://github.com/tattle-made/Uli/assets/97048877/f30975af-e882-4141-83ea-582743b34c4d)

![Screenshot from 2024-04-24 12-04-54](https://github.com/tattle-made/Uli/assets/97048877/801af3dc-0b90-4556-8aa3-980517adc466)

As I can see a PR has been raised for this issue, please let me know if I can raise a PR for the same..

**Comment by aatmanvaidya** [comment]
Hello everyone, thank you so much for your interest and work on this issue, this issue has been resolved with this PR - https://github.com/tattle-made/Uli/pull/546
