### ISSUE TITLE
Users can crowdsource slurs using Uli browser extension

### ISSUE THREAD

**Issue by dennyabrain** [tattle-made/Uli#413]
# Tickets
- [ ] https://github.com/tattle-made/Uli/issues/246
- [ ] https://github.com/tattle-made/Uli/issues/372

**Comment by aatmanvaidya** [comment]
@dennyabrain why did we create a new issue for this?

**Comment by dennyabrain** [comment]
hey @aatmanvaidya you can ignore issues with the label level:initiative. its mainly intended to track multi quarter initiatives. I'm beginning to try this out. I will list all relevant level:feature and level:ticket issues under this on the main comment.
