### ISSUE TITLE
[Bug]: The server restarts when users save preference (i think)

### ISSUE THREAD

**Issue by dennyabrain** [tattle-made/Uli#415]
### Describe the bug

I noticed that our server was crashing when people were saving preference (i think). The error message mentioned the crypter library, so clearly its got to do with encrypting/decrypting the email address that users were sending, even if empty.

This could be related to the bug we noticed while saving preference and it would say "Error saving".

### Steps to reproduce

1. Run the server and plugin
2. Ensure that the plugin is talking to the local development server - it will say development next to the uli icon when you open the extension
3. click save preferences
4. see the server logs 

### Expected behavior

Preferences should be saved with no crashes on the server

### Which operating system are you on?

None

**Comment by aatmanvaidya** [comment]
@dennyabrain if possible can you paste the logs from the error that the server is giving?

**Comment by dennyabrain** [comment]
unfortunately not, coz the server restarted and it erases the logs.

**Comment by dennyabrain** [comment]
but we know that everytime we start the server we see a log like "unable to find cryptr", its essential to debug this now because thats linked too. the bcrypt library we use needs to be updated or something.

**Comment by aatmanvaidya** [comment]
@dennyabrain , strangely, I am not able to see this error on development server on my side, I cannot see it being logged in docker by `api-server`. I tried it on both Windows and Linux. 

I created an account, did CRUD for slur-crowdsource, still couldn't see the error being logged in the `api-server`

**Comment by aatmanvaidya** [comment]
so @dennyabrain , if dependency update was an issue, then @duggalsu updated all the relevant dependencies in this PR - https://github.com/tattle-made/Uli/pull/416. 

I have pulled these changes and I am running them, due to think because of this I am not able to see this error?

**Comment by dennyabrain** [comment]
hmm but it looks like you were not able to recreate this before pulling their changes? Nevertheless, thanks for looking into this. Lets close it for now. Will reopen if we see this in prod again.
