### ISSUE TITLE
Test interface and lexicon together.

### ISSUE THREAD

**Issue by tarunima** [tattle-made/Uli#419]
Test interface and lexicon with two partner organization.

**Comment by tarunima** [comment]
We conducted a session with a partner org one, to see if they found it easy to use the interface to donate slurs and add metadata. Ref #246 

Feedback can be found here: https://app.nuclino.com/TattleRattle/Tattle-Docs/Uli-POV-Crowdsourcing-Flow-9cea67e3-e934-489e-ad31-b2bab36b0bc4

There are two ideas that need to be tested:

- are people motivated to contribute because of the social aspect of the exercise
- are people motivated to contribute because of a synchronized session of contributing (which is how all sessions with partner have gone so far)

So, which model will work best?
- async and social. example: hypothes.is, or wikipedia edits in general where you see edit history 
- sync and not social. example: yesterday's session
- sync and social. example: wikipedia editathons
- async and not social. zotero?

**Comment by dennyabrain** [comment]
Wednesday call with P2

**Comment by dennyabrain** [comment]
Call with P2 is over. Closing this.
