### ISSUE TITLE
Localize Uli for Malayalam Language

### ISSUE THREAD

**Issue by aatmanvaidya** [tattle-made/Uli#422]
### Is your feature request related to a problem? Please describe.

The Uli website and extension can be navigated in Hindi, Tamil and English. The most up-to-date version of the website however is in English. Translate the website, the tool interface and annotation guideline to Malayalam. As part of Uli we also have created certain resources on reporting problematic content on social media platform. These resources could also be translated.

### Describe the solution you would like

written above

**Comment by iajaymk** [comment]
@aatmanvaidya, i would like to translate the web-ui to malayalam. Can I get assigned to this task?

**Comment by aatmanvaidya** [comment]
Hello @iajaymk , please feel free to take this up.

For the scope of this issue, you can just focusing on changing the English text to Malayalam for the following pages on uli website
this is the uli website - https://uli.tattle.co.in/
For now, you can translate the following pages
1. home page - https://uli.tattle.co.in/
2. about page - https://uli.tattle.co.in/about

don't hesitate to reach out in case you need any help!

**Comment by iajaymk** [comment]
@aatmanvaidya Raised a PR #477

**Comment by aatmanvaidya** [comment]
Hello @iajaymk, thank you for the effort and raising the PR. I will review the PR and provide comments on the PR itself, thank you!

**Comment by kaustubhavarma** [comment]
Hello @iajaymk we're conducting an annotation exercise, where we are annotating our list of slurs with additional details such as what makes a word problematic, how severe it is, and so on (more details on our wiki here-https://github.com/tattle-made/Uli/wiki/16-Days-of-Activism-with-Uli). We are having a collaborative session today at 6PM, where participants all annotate a Google sheet with the slur list, and we would like to invite you to contribute as well. Please let us know if you're interested, we will share the details for the same with you.
