### ISSUE TITLE
Feature request - Update axios dependency in plugin

### ISSUE THREAD

**Issue by duggalsu** [tattle-made/Uli#427]
### Is your feature request related to a problem? Please describe.

Update the `axios` dependency in Uli plugin to current version.
- https://www.npmjs.com/package/axios

### Describe the solution you would like

There are breaking changes in the below version that have to be checked and resolved
- https://github.com/axios/axios/releases/tag/v0.27.0

**Comment by Malay-dev** [comment]
Hey @duggalsu, I would like to work on this issue, Please assign it to me...

**Comment by duggalsu** [comment]
hey @Malay-dev , this issue has already been addressed. You are welcome to pick any remaining issues listed here - https://github.com/tattle-made/Uli/issues/426
