### ISSUE TITLE
Submit final event plan to Tinkerspace

### ISSUE THREAD

**Issue by dennyabrain** [tattle-made/Uli#468]
### Is your feature request related to a problem? Please describe.

What does the event with Tinkerspace look like and how it ties with our work this month on 16 days of activism and group annotation exercises.

### Describe the solution you would like

The end goal(s) should align with the group annotation exercises or their end results.

**Comment by dennyabrain** [comment]
Addressing some of the concerns flagged in the email : 

Are we supposed to mandate that the students should either comment under the Github issue or emailing directly to Tattle for showing interest and clarifying doubts?

**Comment by dennyabrain** [comment]
Tentative timeline : 
Nov 8 : Tinkerhub announces the event 
Nov 13 : Tattle Workshop
Nov 14 to Nov 21 : Students work on Issues
Nov 25 to Dec 10 : Students work on proposals

**Comment by dennyabrain** [comment]
Email has been sent to tinkerhub.

**Comment by kaustubhavarma** [comment]
Followed up with the team, awaiting a response.
