### ISSUE TITLE
GPAI paper writing

### ISSUE THREAD

**Issue by tarunima** [tattle-made/Uli#501]
There is a 10 page paper due on community led AI that T needs to present at GPAI Summit on 12th. Need to finish the paper before that.

**Comment by dennyabrain** [comment]
slides being worked on. Will be done by sunday. 
Paper by 18th December.

**Comment by tarunima** [comment]
https://docs.google.com/document/d/1ZL9P65IZvqY6hAlW4q7inDz3cg4Sjk5WH1TQQOTXx7I/edit

**Comment by tarunima** [comment]
presentation done on Tuesday.

**Comment by tarunima** [comment]
we were aiming for 22nd but won't meet it. Possibly end of year.

**Comment by tarunima** [comment]
paper submitted.
