### ISSUE TITLE
Flesh out report body

### ISSUE THREAD

**Issue by dennyabrain** [tattle-made/Uli#503]
We have this outline:

https://app.nuclino.com/TattleRattle/Tattle-Docs/Paper-High-Level-Structure-339d5779-4137-40f9-aca3-d53af91d0ea6

In iteration 4 we are specifically focusing on fleshing out Methodology and Literature review.

**Comment by sidm92** [comment]
Broad framework flow of report on Google Docs:
https://docs.google.com/document/d/17OcAQgXyqAoV92TrnO7VoWP1Syg3S3Ep3EXAodpmRnc/edit?usp=drive_link

Report being written out here: https://docs.google.com/document/d/1tRvJyBGpD6zPbrenRi63R6HrDsVZdhrs6ZNsyHKJvw0/edit
Currently section 2/5, "Motivation"

**Comment by dennyabrain** [comment]
Power Analysis
Power differential between annotators and companies

Some version of the report will be out by Saturday Morning

**Comment by sidm92** [comment]
Power analysis and relationship between annotators and companies has been fleshed out
Motivation section completed, analysis largely done.
Fixing sections on Intro and relevance to Uli today, and linking to interviews. This will complete non-interview section of report.

**Comment by sidm92** [comment]
Writing of abstract, intro, motivation and lit review is completed. All sections apart from interviews.
https://docs.google.com/document/d/1tRvJyBGpD6zPbrenRi63R6HrDsVZdhrs6ZNsyHKJvw0/edit
