### ISSUE TITLE
Make metadata discoverable in the browser extension

### ISSUE THREAD

**Issue by dennyabrain** [tattle-made/Uli#519]

**Comment by dennyabrain** [comment]
Figured out ways to extract slur.

**Comment by aatmanvaidya** [comment]
Adding text before and after a word in HTML
- https://stackoverflow.com/questions/7378097/add-text-before-or-after-an-html-element
- https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp
- https://www.w3schools.com/jsref/met_node_insertadjacenttext.asp
- https://www.w3schools.com/jsref/met_node_insertbefore.asp

**Comment by aatmanvaidya** [comment]
working prototype video - https://youtu.be/rsJpmKdfigQ

**Comment by aatmanvaidya** [comment]
will work on making the tooltip dynamic and integrating it into the plugin today

**Comment by aatmanvaidya** [comment]
Dynamic tooltip resources - 
- https://codepen.io/andrewgunn/pen/kQKaBz
- https://codeshack.io/pure-css3-html5-tooltips/
- https://github.com/ghosh/microtip/tree/master

**Comment by aatmanvaidya** [comment]
was able to add the information symbol in front of words via the plugin, requires bug fixes.
