### ISSUE TITLE
Blog Draft on Persistance of Harms

### ISSUE THREAD

**Issue by kaustubhavarma** [tattle-made/Uli#525]
We need to write a blog (~800 words) on the persistance of oGBV from one source (i.e individual) online.
- [x] Secondary research on the issue: references so far are- 

> https://www.orfonline.org/expert-speak/the-great-gender-glitch; 

> https://www.kictanet.or.ke/cross-platform-ogbv-an-insidious-problem/; 

> https://unesdoc.unesco.org/ark:/48223/pf0000383044; 

> Meri Trustline Report

> CIGI Report: https://www.cigionline.org/static/documents/SaferInternet_Special_Report.pdf

> https://rebootingsocialmedia.org/2022/12/01/from-emergency-to-prevention-protecting-journalists-from-online-abuse/

> https://onlineharassmentfieldmanual.pen.org/defining-online-harassment-a-glossary-of-terms/

> Julie Posetti, Kalina Bontcheva and Nabeelah Shabbir, ‘The Chilling: Assessing Big Tech’s Response to Online Violence Against Women Journalists’ (May 2022, UNESCO)

- [x] Initial draft

**Comment by kaustubhavarma** [comment]
The draft has been prepared and is available on nuclino.

**Comment by dennyabrain** [comment]
@kaustubhavarma @tarunima has this blog been published?
