### ISSUE TITLE
Schedule Sessions for Slur List Contributions with Partner Orgs

### ISSUE THREAD

**Issue by kaustubhavarma** [tattle-made/Uli#530]
- [x] Email partner organisations about online sessions to contribute to the slur list
- [x] Schedule 2 sessions a week at the most, 1 hour long
- [x] Send Calendly invites

**Comment by dennyabrain** [comment]
waiting on confirmation with partner orgs

**Comment by kaustubhavarma** [comment]
- meeting with FII completed last week

To do:
- [ ] Follow up with POV (haven't received response yet)
- [ ] Email the organisations with Calendly links by tomorrow latest

**Comment by kaustubhavarma** [comment]
- email sent to partner organisations
- Google calendar invites will be sent by end of the week following responses to Doodle link.
