### ISSUE TITLE
Conduct crowdsourcing sessions with partner organizations

### ISSUE THREAD

**Issue by tarunima** [tattle-made/Uli#540]
Synchronous online sessions are being conducted on the following dates with the partner organisations:

1. April 9th
2. April 16th
3. April 23th 
4. April 24th
5. April 30th

**Comment by kaustubhavarma** [comment]
The first two sessions have been completed.

**Comment by kaustubhavarma** [comment]
All sessions have been completed.

**Comment by kaustubhavarma** [comment]
Second Leg of sessions to be underway from August/September
