### ISSUE TITLE
[uli-website]: order blogs in descending order of date

### ISSUE THREAD

**Issue by aatmanvaidya** [tattle-made/Uli#557]
The task is to display the blogs in descending order of the date on the Blogs index page (https://uli.tattle.co.in/blog/). The most recent blog should be on top. 

![image](https://github.com/tattle-made/Uli/assets/56875084/2794e311-5dba-470c-a79c-08f16de0d9f1)

- To fix this issue the `graphql` query in this [file](https://github.com/tattle-made/Uli/blob/main/uli-website/src/pages/blog/index.jsx) will have to be modified.  
- while devleoping the site locally, the `graphql` schema can be found at `http://localhost:8000/___graphql`
- The `uli-website` renders mdx files as blog posts. This is a helpful [guide](https://www.gatsbyjs.com/docs/how-to/routing/adding-markdown-pages/#frontmatter-for-metadata-in-markdown-files) on understanding how markdown pages are added to the website.

**Comment by Shubh8899** [comment]
@aatmanvaidya  I would like to work on this one. Can you assign it to me?

**Comment by aatmanvaidya** [comment]
Hi @Shubh8899 , please feel free to take it up, assigning it to you!

**Comment by aatmanvaidya** [comment]
this issue is fixed here - https://github.com/tattle-made/Uli/pull/563
