### ISSUE TITLE
Refactor API endpoints into individual files

### ISSUE THREAD

**Issue by dennyabrain** [tattle-made/Uli#559]
All the handlers for every API endpoint is located in one file - https://github.com/tattle-made/Uli/blob/main/browser-extension/api-server/index.js
This was good when we started out, but its difficult to maintain as the app grows and new maintainers join. Lets refactor them into endpoint specific files. 

Please suggest your idea for how you would refactor the endpoints and we can critique it. When approved you can start the implementation and make a PR

**Comment by dennyabrain** [comment]
@hardik-pratap-singh  tagging for your visibility

**Comment by hardik-pratap-singh** [comment]
Hello @dennyabrain 
I want to work on this issue. 
Kindly assign it to me.

**Comment by hardik-pratap-singh** [comment]
Hey @dennyabrain @aatmanvaidya !
I am here with an idea to solve the above issue.


I am planning to create two separate folders (inspired from MVC architecture) :
1) routes
2) controllers

Within each of these folders, I am going to have files which will contain similar kind of routes.

Folder structure will look something like this : 
![image](https://github.com/tattle-made/Uli/assets/97048877/e2f20492-ab56-4f87-9d48-3fb73186c9fc)

For eg : 

This is how `routes/slur.js` will look like 
![image](https://github.com/tattle-made/Uli/assets/97048877/8c66a235-574f-4c55-91f1-a55a4ce55ed0)

And these functions such as `createSlur`, `updateSlur`, `deleteSlur`, etc. will be implemented in `controllers/slur.js`

**Comment by aatmanvaidya** [comment]
Hi @hardik-pratap-singh 
this looks good, I think you can proceed with this for now!

@dennyabrain is currently away so give us some time till early next week to provide detailed feedback (if needed) on the folder structure and nomenclature.

**Comment by dennyabrain** [comment]
Looks good to me too. You can start the implementation and make a PR for the work in progress state. We can give granular feedback at that point.
