### ISSUE TITLE
Firefox Add-on

### ISSUE THREAD

**Issue by uncannyjish** [tattle-made/Uli#603]
### Is your feature request related to a problem? Please describe.

The biggest problem is chrome. Google has done very little to support net neutrality or the pure essence of being a browser.

### Describe the solution you would like

Would like this extension to be ported or built for Firefox and other open source browsers that take user privacy seriously.

**Comment by dennyabrain** [comment]
Hey @uncannyjish the extension works on Firefox too. You can download it from Firefox store or find the Firefox specific instructions in the project wiki?
