### ISSUE TITLE
Write tests for show slur metadata functions

### ISSUE THREAD

**Issue by aatmanvaidya** [tattle-made/Uli#612]
write unit tests for core show slur metadata functions - [existing folder for tests](https://github.com/tattle-made/Uli/tree/main/browser-extension/plugin/test)

**Comment by hardik-pratap-singh** [comment]
Please assign this issue to me.

**Comment by hardik-pratap-singh** [comment]
Hello @dennyabrain @aatmanvaidya ! 
I have finished writing tests for all five functions that I am using for solving issue #544 

![image](https://github.com/user-attachments/assets/2182ea1c-3b3d-45dc-8768-01cb9f2fa0f5)

Moving `enableSlurMetadata.test.js` inside [existing folder for tests](https://github.com/tattle-made/Uli/tree/main/browser-extension/plugin/test)

**Comment by hardik-pratap-singh** [comment]
Tests integration done..
![image](https://github.com/user-attachments/assets/f28ef2d9-4ccd-4951-b175-09f1a257778d)

PS: To run this particular test, you can use `npm run test:api -t 'enable'`

**Comment by aatmanvaidya** [comment]
resolved in https://github.com/tattle-made/Uli/pull/615
