### ISSUE TITLE
Show date on Uli Blog page

### ISSUE THREAD

**Issue by tarunima** [tattle-made/Uli#639]
### Is your feature request related to a problem? Please describe.

Currently the date on which an article is published is not on this blog page: https://uli.tattle.co.in/blog/. 

### Describe the solution you would like

Date should also be visible alongside title and author. The articles should also be organized chronologically.

**Comment by dennyabrain** [comment]
@mahimahto the uli website is written in gatsby. you have some experience with it, see if you can try solving this issue.

**Comment by Mahimahto** [comment]
https://github.com/tattle-made/Uli/pull/640
